manipulate_wp: massive overhall from the german open 2024
carologistics/fawkes-robotino pull request #657
Opened 2024-05-04 13:27 UTC by techtasie

We changed the MP to now use the center of the laser-line distance into respect to the ideal machine position.

2024-05-04 16:31 UTC, MatteoTschesche commented
You should mention that laser-lines using fawkes is not supported anymore.

2024-05-14 12:03 UTC, MatteoTschesche requested changes
Thanks for the work, here is some feedback.

2024-05-30 08:56 UTC, techtasie commented on src/lua/skills/robotino/manipulate_wp.lua
> +  if fsm.vars.map_pos ~= false then
okay i will extract out all safe put stuff bit hard to seperate but you have a fair point.

2024-05-30 09:01 UTC, techtasie commented on src/lua/skills/robotino/manipulate_wp.lua
> +            best_distance = distance
Thank you!

2024-06-11 18:10 UTC, MatteoTschesche approved these changes
Nice work, thanks!

2024-06-11 18:10 UTC, merged