rcll-central: approach BS from free side when in use
carologistics/fawkes-robotino pull request #682
Opened 2024-06-14 14:52 UTC by kalrasamridhi7

2024-07-02 12:33 UTC, TarikViehmann requested changes
Good job, it is also tested in practice.
But have a few small comments that should be addressed.

2024-07-02 12:33 UTC, TarikViehmann commented on src/clips-specs/rcll-central/derived-predicates/bs-side-in-use.clp
> +	(not (domain-fact (name bs-side-in-use) (param-values bs $?)))
```suggestion
	(not (domain-fact (name bs-side-in-use) (param-values ?bs $?)))
```
and this precond needs to go after the one that grounds ths ?bs variable

2024-07-02 12:33 UTC, TarikViehmann commented on src/clips-specs/rcll-central/derived-predicates/bs-side-in-use.clp
> +	(wm-fact (key domain fact mps-type args? $? ?bs $? BS $?))
```suggestion
	(domain-fact (name mps-type) (param-values ?bs BS))
```

2024-07-02 12:33 UTC, TarikViehmann commented on src/clips-specs/rcll-central/derived-predicates/bs-side-in-use.clp
> +	(wm-fact (key domain fact mps-type args? $? ?bs $? BS $?))
```suggestion
	(domain-fact (name mps-type) (param-values ?bs BS))
```

2024-07-04 13:09 UTC, kalrasamridhi7 commented
Addressed the requested changes

2024-07-04 16:55 UTC, TarikViehmann approved these changes
Thank you very much!

2024-07-04 16:55 UTC, merged