rcll-central: moves robot out of the way when goal exceeds retry limit
carologistics/fawkes-robotino pull request #707
Opened 2024-07-17 18:46 UTC by kalrasamridhi7

2024-07-17 19:41 UTC, kalrasamridhi7 commented
TODO: re-create retracted move-out-of-way goals after their completion

2024-07-18 08:26 UTC, TarikViehmann requested changes
Good job, i have a few comments

2024-07-18 08:26 UTC, TarikViehmann commented on src/clips-specs/rcll-central/goal-production.clp
> +  (goal-meta (goal-id ?goal-id) (assigned-to ?robot))
This rule needs appropriate priority e.g., `?*SALIENCE-GOAL-EXECUTABLE-CHECK*`, because otherwise it will be ignored on selection.

2024-07-18 08:26 UTC, TarikViehmann commented on src/clips-specs/rcll-central/goal-reasoner.clp
> +;  (declare (salience (+ 2 ?*SALIENCE-GOAL-FORMULATE*)))
remove this

2024-07-18 08:26 UTC, TarikViehmann commented on src/clips-specs/rcll-central/goal-reasoner.clp
> +	(do-for-all-facts ((?og goal) (?ogm goal-meta))
do we actually need this?
The goal is not assigned to a robot anymore after this rule, this should trigger the priority reset already (rule goal-production-change-priority-move-out-of-way)
Hence i would remove the innder do-for-all-facts

2024-07-18 08:28 UTC, TarikViehmann commented on src/clips-specs/rcll-central/goal-production.clp
> +  (goal-meta (goal-id ?goal-id) (assigned-to ?robot))
Then you can also simplify this rule and remove the ?or, essentially just updating the rule during executability check

2025-03-06 18:53 UTC, merged